apiVersion: v1
kind: Service
metadata:
  name: redis-oauth2-server
  labels:
    app: redis-oauth2-server
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: redis-oauth2-server
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-oauth2-server
  labels:
    app: redis-oauth2-server
spec:
  selector:
    matchLabels:
      app: redis-oauth2-server
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis-oauth2-server
        tier: frontend
    spec:
      containers:
      - image: 192.168.0.210:5000/redis-oauth2-server:1.0.0
        name: redis-oauth2-server
        env:
        - name: NODE_ENV
          value: production
        - name: REDIS_URL
          value: redis://@redis-master:6379
        ports:
        - containerPort: 3001
