apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app2
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-app2
    app.kubernetes.io/instance: {{ .Release.Name }}-app2
    app.kubernetes.io/version: 1.0.0
    service: {{ .Release.Name }}-app2
spec:
  type: ClusterIP
  ports:
  - port: 8091
    name: {{ .Release.Name }}-app2
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-app2
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    version: {{ .Chart.AppVersion }}-{{ .Values.mod.version }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app2-{{ .Values.deploy.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-app2
    app.kubernetes.io/instance: {{ .Release.Name }}-app2
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    version: {{ .Chart.AppVersion }}-{{ .Values.mod.version }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-app2
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-app2
        app.kubernetes.io/instance: {{ .Release.Name }}-app2
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        version: {{ .Chart.AppVersion }}-{{ .Values.mod.version }}
    spec:
      containers:
      - name: {{ .Release.Name }}-app2
        image: "{{ .Values.smpc.image }}:{{ .Chart.AppVersion }}"
        ports:
        - containerPort: 8091
        imagePullPolicy: Always
        env:
        - name: HOST_IP
          value: "{{ .Release.Name }}-app2"
        - name: REDIS_ADDRS
          value: {{ .Values.common.redis.addrs | quote }}
        - name: MOD_SERVICE_URI
          value: {{ .Values.mod.modServiceUri | quote }}
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      - name: {{ .Release.Name }}-mod-9001
        image: "{{ .Values.mod.image }}:{{ .Chart.AppVersion }}-{{ .Values.mod.version }}"
        ports:
        - containerPort: 9001
        imagePullPolicy: Always
        env:
        - name: HOST_IP
          value: "{{ .Release.Name }}-mod-9001"
        - name: MOD_VERSION
          value: {{ .Values.mod.version | quote }}
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      - name: {{ .Release.Name }}-mod-9002
        image: "{{ .Values.mod.image }}:{{ .Chart.AppVersion }}-{{ .Values.mod.version }}"
        ports:
        - containerPort: 9002
        imagePullPolicy: Always
        env:
        - name: HOST_IP
          value: "{{ .Release.Name }}-mod-9002"
        - name: MOD_VERSION
          value: {{ .Values.mod.version | quote }}
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
